"""
agent.py
--------
The orchestrator. Given a single automation_schedules row, this runs the
full pipeline end to end:

    1. Generate script  (script_generator)
    2. Render video      (video_creator)
    3. Upload to YouTube (youtube_uploader)

At each step it updates the `videos` table so the frontend can show live
status ("generating_script" -> "rendering" -> "uploading" -> "published"
or "failed"). This is the function both the scheduler loop and the manual
"run now" API endpoint call.
"""

from datetime import datetime, timedelta, timezone

from app import db
from app.script_generator import generate_script
from app.video_creator import render_video
from app.youtube_uploader import upload_video


def _compute_next_run(frequency: str, cron_expression: str | None) -> datetime:
    """
    Very simple scheduling for Phase 2. 'daily' and 'weekly' just add a
    fixed offset. 'custom' (real cron parsing) is a good candidate to wire
    up with a library like `croniter` in a later phase.
    """
    now = datetime.now(timezone.utc)
    if frequency == "weekly":
        return now + timedelta(days=7)
    return now + timedelta(days=1)  # default: daily


def run_schedule(schedule: dict) -> dict:
    """
    Execute one automation_schedules row. Returns the final video record
    (as a dict) for logging/inspection. Never raises — failures are caught
    and written to the video's error_message so a bad job doesn't crash
    the whole scheduler loop.
    """
    schedule_id = schedule["id"]
    user_id = schedule["user_id"]
    connection_id = schedule["youtube_connection_id"]
    topic_prompt = schedule["topic_prompt"]

    # ---- Pro-tier gate ----
    # This is the actual enforcement point for "only Pro users can run the
    # automated agent." A schedule row existing is not enough — RLS only
    # governs who can write a row, not what it's allowed to trigger, and a
    # subscription can lapse (payment failure, cancellation) after a
    # schedule was created while still Pro. We check fresh, every run.
    if not db.is_pro_user(user_id):
        next_run = _compute_next_run(schedule["frequency"], schedule.get("cron_expression"))
        db.mark_schedule_run(schedule_id, next_run)
        return {
            "skipped": True,
            "reason": "not_pro",
            "schedule_id": schedule_id,
        }

    video_record = None

    try:
        # ---- 1. Generate script ----
        script = generate_script(topic_prompt)
        video_record = db.create_video_record(
            user_id=user_id,
            schedule_id=schedule_id,
            title=script.title,
            script=script.full_text,
        )
        video_id = video_record["id"]

        # ---- 2. Render video ----
        db.update_video_status(video_id, "rendering")
        output_path = render_video(script, output_filename=f"{video_id}.mp4")
        db.update_video_status(video_id, "uploading", video_url=str(output_path))

        # ---- 3. Upload to YouTube ----
        youtube_video_id = upload_video(
            connection_id=connection_id,
            file_path=output_path,
            title=script.title,
            description="Automatically generated by AutoTube AI.",
            privacy_status="private",  # keep private until the user reviews it
        )
        db.update_video_status(video_id, "published", youtube_video_id=youtube_video_id)

        # ---- 4. Advance the schedule ----
        next_run = _compute_next_run(schedule["frequency"], schedule.get("cron_expression"))
        db.mark_schedule_run(schedule_id, next_run)

        return {
            "video_id": video_id,
            "youtube_video_id": youtube_video_id,
            "status": "published",
        }

    except Exception as exc:  # noqa: BLE001 — intentionally broad: one bad job shouldn't kill the loop
        if video_record:
            db.update_video_status(video_record["id"], "failed", error_message=str(exc))
        # Still push next_run forward so a persistently broken schedule
        # doesn't spin-retry every poll interval.
        next_run = _compute_next_run(schedule["frequency"], schedule.get("cron_expression"))
        db.mark_schedule_run(schedule_id, next_run)
        return {"error": str(exc), "schedule_id": schedule_id}
